        <!--Imprime la tabla de turnos, nuestros items.-->
    <?php require_once './templates/layout/header.phtml'; 
?>

        <div id="turnos" class="container my-5">
        <h2 class="text-center mb-4">Turnos Ocupados</h2>
        <table class="table table-striped">
            <thead>
            <tr>
                    <th>Paciente Id</th>
                    <th>Fecha</th>
                    <th>Hora</th>
                    <th>Detalles</th>
                </tr>
            </thead>
            <tbody>
        <?php foreach ($turns as $turn) : ?>
                <tr>
                    <td><?=$turn->id?></td>
                    <td><?=$turn->hora?></td>
                    <td><?=$turn->fecha?></td>
                    <td><a href="detalle/<?=$turn->id?>">Ver más</a></td>
                    <td><button class="btn btn-success btn-sm" data-bs-toggle="modal" data-bs-target="#addTurnoModal">Agregar</button></td>
                    <td><button class="btn btn-warning btn-sm" data-bs-toggle="modal" data-bs-target="#editTurnoModal" data-id="001" data-nombre="Juan Pérez" data-fecha="2024-10-15" data-especialidad="Cardiología" data-medico="Dr. González">Editar</button></td>
                    <td><button class="btn btn-danger btn-sm" data-bs-toggle="modal" data-bs-target="#deleteTurnoModal" data-id="001">Eliminar</button></td>
                </tr>            
            <?php endforeach; ?>
            </tbody>
        </table>
        </div>
        <!-- SI ES ADMINISTRADOR VE ESTOS BOTONES y sus FUNCIONES -->


 <!--Modal para agregar Turno -->
  <div class="modal fade" id="addTurnoModal" tabindex="-1" aria-labelledby="addTurnoModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="addTurnoModalLabel">Agregar Turno</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <form>
            <div class="mb-3">
              <label for="pacienteNombre" class="form-label">Nombre del Paciente</label>
              <input type="text" class="form-control" id="pacienteNombre" required>
            </div>
            <div class="mb-3">
              <label for="fechaTurno" class="form-label">Fecha</label>
              <input type="date" class="form-control" id="fechaTurno" required>
            </div>
            <div class="mb-3">
              <label for="especialidadTurno" class="form-label">Hora</label>
              <input type="time" class="form-control" id="horaTurno" required>
            </div>
            <div class="mb-3">
              <label for="medicoTurno" class="form-label">Médico</label>
              <input type="text" class="form-control" id="medicoTurno" required>
            </div>
          </form>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
          <button type="button" class="btn btn-primary">Agregar Turno</button>
        </div>
      </div>
    </div>
  </div>

   <!--Modal para editar Turno -->
  <div class="modal fade" id="editTurnoModal" tabindex="-1" aria-labelledby="editTurnoModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="editTurnoModalLabel">Editar Turno</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <form>
            <div class="mb-3">
              <label for="editPacienteNombre" class="form-label">Nombre del Paciente</label>
              <input type="text" class="form-control" id="editPacienteNombre" required>
            </div>
            <div class="mb-3">
              <label for="editFechaTurno" class="form-label">Fecha</label>
              <input type="date" class="form-control" id="editFechaTurno" required>
            </div>
            <div class="mb-3">
              <label for="editEspecialidadTurno" class="form-label">Hora</label>
              <input type="time" class="form-control" id="editEspecialidadTurno" required>
            </div>
            <div class="mb-3">
              <label for="editMedicoTurno" class="form-label">Médico</label>
              <input type="text" class="form-control" id="editMedicoTurno" required>
            </div>
          </form>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
          <button type="button" class="btn btn-primary">Guardar Cambios</button>
        </div>
      </div>
    </div>
  </div>

  <!-- Modal para eliminar Turno -->
  <div class="modal fade" id="deleteTurnoModal" tabindex="-1" aria-labelledby="deleteTurnoModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="deleteTurnoModalLabel">Eliminar Turno</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          ¿Estás seguro de que deseas eliminar este turno?
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
          <button type="button" class="btn btn-danger">Eliminar</button>
        </div>
      </div>
    </div>
  </div>

   <!--Modal para agregar Paciente-->
  <div class="modal fade" id="addPacienteModal" tabindex="-1" aria-labelledby="addPacienteModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="addPacienteModalLabel">Agregar Paciente</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <form>
            <div class="mb-3">
              <label for="pacienteID" class="form-label">ID Paciente</label>
              <input type="text" class="form-control" id="pacienteID" required>
            </div>
            <div class="mb-3">
              <label for="pacienteNombre" class="form-label">Nombre</label>
              <input type="text" class="form-control" id="pacienteNombre" required>
            </div>
            <div class="mb-3">
              <label for="pacienteEdad" class="form-label">Edad</label>
              <input type="number" class="form-control" id="pacienteEdad" required>
            </div>
            <div class="mb-3">
              <label for="pacienteGenero" class="form-label">Género</label>
              <select class="form-select" id="pacienteGenero" required>
                <option value="">Seleccionar...</option>
                <option value="masculino">Masculino</option>
                <option value="femenino">Femenino</option>
              </select>
            </div>
            <div class="mb-3">
              <label for="pacienteEmail" class="form-label">Correo Electrónico</label>
              <input type="email" class="form-control" id="pacienteEmail" required>
            </div>
          </form>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
          <button type="button" class="btn btn-primary">Agregar Paciente</button>
        </div>
      </div>
    </div>
  </div>

  <!--Modal para editar Paciente -->
  <div class="modal fade" id="editPacienteModal" tabindex="-1" aria-labelledby="editPacienteModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="editPacienteModalLabel">Editar Paciente</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <form>
            <div class="mb-3">
              <label for="editPacienteID" class="form-label">ID Paciente</label>
              <input type="text" class="form-control" id="editPacienteID" required>
            </div>
            <div class="mb-3">
              <label for="editPacienteNombre" class="form-label">Nombre</label>
              <input type="text" class="form-control" id="editPacienteNombre" required>
            </div>
            <div class="mb-3">
              <label for="editPacienteEdad" class="form-label">Edad</label>
              <input type="number" class="form-control" id="editPacienteEdad" required>
            </div>
            <div class="mb-3">
              <label for="editPacienteGenero" class="form-label">Género</label>
              <select class="form-select" id="editPacienteGenero" required>
                <option value="">Seleccionar...</option>
                <option value="masculino">Masculino</option>
                <option value="femenino">Femenino</option>
              </select>
            </div>
            <div class="mb-3">
              <label for="editPacienteEmail" class="form-label">Correo Electrónico</label>
              <input type="email" class="form-control" id="editPacienteEmail" required>
            </div>
          </form>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
          <button type="button" class="btn btn-primary">Guardar Cambios</button>
        </div>
      </div>
    </div>
  </div>

   <!--Modal para eliminar Paciente -->
  <div class="modal fade" id="deletePacienteModal" tabindex="-1" aria-labelledby="deletePacienteModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="deletePacienteModalLabel">Eliminar Paciente</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          ¿Estás seguro de que deseas eliminar este paciente?
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
          <button type="button" class="btn btn-danger">Eliminar</button>
        </div>
      </div>
    </div>
  </div>
  