        <!--Imprime la tabla de turnos, nuestros items.-->
        <?php require_once './templates/layout/header.phtml';
        ?>
        <div id="turnos" class="container my-5">
          <h2 class="text-center mb-4">Turnos Ocupados</h2>
          <table class="table table-striped">
            <thead>
              <tr>
                <th>Médico</th>
                <th>Fecha</th>
                <th>Hora</th>
                <th>Detalles</th>
                <th>
                  <!--Boton "Agregar"-->
                  <div class="text-center">
                <td>
                  <!--Si el usuario esta logueado mostrar boton "Agregar"-->
                <?php if (!empty($_SESSION['ID_USER'])): ?>
                  <a class="btn text-white btn-success btn-sm" data-bs-toggle="modal" data-bs-target="#addTurnoModal">Agregar</a></td>
                <?php endif; ?>
        </div>
        </th>
        </tr>
        </thead>
        <tbody>
          <?php foreach ($turns as $turn) : ?>
            <tr>
              <td><?= $turn->medico ?></td>
              <td><?= $turn->fecha ?></td>
              <td><?= $turn->hora ?></td>
              <td><a class="btn btn-link text-black" href="detalle/<?= $turn->id ?>">Ver más</a></td>
              <!--Si estas logueado, mostrar botones-->
              <?php if (!empty($_SESSION['ID_USER'])): ?>
              <!--Boton "Editar"-->
              <td><a href= "<?=BASE_URL ?>updateTurns/<?= $turn->id ?>" class="btn text-white btn-warning btn-sm" data-bs-toggle="modal" data-bs-target="#editTurnoModal">Editar</a></td>
              <!--Boton "Eliminar"-->
              <td><a href="<?= BASE_URL ?>deleteTurns/<?= $turn->id ?>" class="btn text-white btn-danger btn-sm">Eliminar</a></td>
              <?php endif; ?>
            </tr>
          <?php endforeach; ?>
        </tbody>
        </table>
        </div>

        <!-- SI ES ADMINISTRADOR VE ESTOS BOTONES y sus FUNCIONES -->

        <!--Form para agregar Turno -->
        <div class="modal fade" id="addTurnoModal" tabindex="-1" aria-labelledby="addTurnoModalLabel" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="addTurnoModalLabel">Agregar Turno</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
              </div>
              <div class="modal-body">
                <form action="createTurns" method="POST">
                  <div class="mb-3">
                    <label for="fechaTurno" class="form-label">Fecha</label>
                    <input type="date" name="fecha" class="form-control" id="fechaTurno" required>
                  </div>
                  <div class="mb-3">
                    <label for="especialidadTurno" class="form-label">Hora</label>
                    <input type="time" name="hora" class="form-control" id="horaTurno" required>
                  </div>
                  <div class="mb-3">
                    <label for="medicoTurno" class="form-label">Nro. Consultorio</label>
                    <input type="text" name="consultorio" class="form-control" id="consultorioTurno" required>
                  </div>
                  <div class="mb-3">
                    <label for="medicoTurno" class="form-label">Médico</label>
                    <input type="text" name="medico" class="form-control" id="medicoTurno" required>
                  </div>
                  <div class="mb-3">
                    <Label>Nombre del Paciente</Label>
                    <select name="id_paciente" for="medicoTurno" class="form-label">
                      <!--select con nombres de los pacientes, si HAY categorias-->
                    <?php if(!empty($categories)):?>
                    <?php foreach($categories as $category):?>
                    <option value="<?= $category->id ?>"> <?= $category->nombre?></option> 
                    <?php endforeach; ?>
                    <!--select con msj, si NO HAY categorias-->
                    <?php else: ?>
                      <option>No hay pacientes!</option>
                      <?php endif; ?>
                    </select>
                    </div>
                  <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                  <!--Si no hay categorias, no puede agregar un turno-->
                  <?php if(!empty($categories)) : ?>
                    <button type="submit" class="btn btn-primary">Agregar Turno</button>
                  <?php endif; ?>
                </form>
              </div>
              <div class="modal-footer">
              </div>
            </div>
          </div>
        </div>

        <!--Form para editar Turno -->
        <div class="modal fade" id="editTurnoModal" tabindex="-1" aria-labelledby="editTurnoModalLabel" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="editTurnoModalLabel">Editar Turno</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
              </div>
              <div class="modal-body">
                    <!--TOMA SIEMPRE EL ID DEL ULTIMO, YA QUE EL FORMULARIO ESTÁ EN UN MODAL. 
                    UNA SOLUCIÓN SERIA CREAR EL FORMULARIO SIN MODAL EN UNA PÁGINA NUEVA.-->
                <form action="<?= BASE_URL ?>updateTurns/<?= $turn->id ?>" method="POST">
                  <div class="mb-3">
                    <label for="editFechaTurno" class="form-label">Fecha</label>
                    <input type="date" name="fecha" class="form-control" id="editFechaTurno" required>
                  </div>
                  <div class="mb-3">
                    <label for="editEspecialidadTurno" class="form-label">Hora</label>
                    <input type="time" name="hora" class="form-control" id="editEspecialidadTurno" required>
                  </div>
                  <div class="mb-3">
                    <label for="medicoTurno" class="form-label">Consultorio</label>
                    <input type="text" name="consultorio" class="form-control" id="consultorioTurno" required>
                  </div>
                  <div class="mb-3">
                    <label for="editMedicoTurno" class="form-label">Médico</label>
                    <input type="text" name="medico" class="form-control" id="editMedicoTurno" required>
                  </div>
                  <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                  <button type="submit" method="POST" class="btn btn-primary">Guardar Cambios</button>
                </form>
              </div>
              <div class="modal-footer">
              </div>
            </div>
          </div>
        </div>