<?php require_once './templates/layout/header.phtml';
?>
<?php if ($turns == null) : ?>
    <!--Si el paciente no tiene turnos-->
    <div class="container mt-5">
        <div class="alert alert-danger text-center" role="alert">
            <h3 class="noturns font-weight-bold">¡SIN INFORMACIÓN!</h3>
            <p>Actualmente no tenemos ningún turno disponible para este expediente, vuelve más tarde.</p>
        </div>
    </div>
<?php else: ?>
        <h3>¡Turnos del paciente!</h3>
<?php foreach ($turns as $turn) : ?>
    <div class="container mt-4">
        <table class="table table-striped table-hover mt-3" style="border: 1px solid #bcd4e6;">
            <thead>
                <tr>
                    <th colspan="2" class="text-primary" style="font-size: 1.5em;">Detalles del Turno</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <th scope="row" class="bg-light text-secondary">ID</th>
                    <td><?= $turn->id ?></td>
                </tr>
                <tr>
                    <th scope="row" class="bg-light text-secondary">Fecha</th>
                    <td><?= $turn->fecha ?></td>
                </tr>
                <tr>
                    <th scope="row" class="bg-light text-secondary">Hora</th>
                    <td><?= $turn->hora ?></td>
                </tr>
                <tr>
                    <th scope="row" class="bg-light text-secondary">Consultorio</th>
                    <td><?= $turn->consultorio ?></td>
                </tr>
                <tr>
                    <th scope="row" class="bg-light text-secondary">Médico</th>
                    <td><?= $turn->medico ?></td>
                </tr>
                <tr>
                    <th scope="row" class="bg-light text-secondary">ID Paciente</th>
                    <td><?= $turn->id_paciente ?></td>
                </tr>
            </tbody>
        </table>
    </div>
<?php endforeach;
endif; ?>