<?php require_once './templates/layout/header.phtml'; ?>
<div class="container mt-4">
    <table class="table table-striped table-hover mt-3" style="border: 1px solid #bcd4e6;">
        <thead>
            <tr>
                <th colspan="2" class="text-primary text-center" style="font-size: 1.5em;">Detalles del Turno</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <th scope="row" class="bg-light text-secondary">ID</th>
                <td><?= $turn->id ?></td>
            </tr>
            <tr>
                <th scope="row" class="bg-light text-secondary">Fecha</th>
                <td><?= $turn->fecha ?></td>
            </tr>
            <tr>
                <th scope="row" class="bg-light text-secondary">Hora</th>
                <td><?= $turn->hora ?></td>
            </tr>
            <tr>
                <th scope="row" class="bg-light text-secondary">Médico</th>
                <td><?= $turn->medico ?></td>
            </tr>
            <tr>
                <th scope="row" class="bg-light text-secondary">Paciente</th>
                <td><?= $persona->nombre ?> <?= $persona->apellido ?></td>
            </tr>
            <tr>
                <th scope="row" class="bg-light text-secondary">Consultorio</th>
                <td><?= $turn->consultorio ?></td>
            </tr>
        </tbody>
    </table>
</div>
