        <div id="turnos" class="container my-5">
        <h2 class="text-center mb-4">Turnos Ocupados</h2>
        <table class="table table-striped">
            <thead>
            <tr>
                    <th>Paciente</th>
                    <th>Fecha</th>
                    <th>Hora</th>
                    <th>Detalles</th>
                </tr>
            </thead>
            <tbody>
        <?php foreach ($turns as $turn) : ?>
                <tr>
                    <td><?=$turn->id?></td>
                    <td><?=$turn->hora?></td>
                    <td><?=$turn->fecha?></td>
                    <td><a href="detalle/<?=$turn->id?>">Ver más</a></td>
                </tr>            
            <?php endforeach; ?>
        
                
            
