<?php require_once './templates/layout/header.phtml';
?>

    <section class="container my-5">
        <h2 class="text-center">Preguntas Frecuentes</h2>
        <di class="accordion" id="faqAccordion">
          <div class="accordion-item">
            <h2 class="accordion-header" id="headingOne">
              <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
                1. ¿Cuáles son los horarios de atención?
              </button>
            </h2>
            <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#faqAccordion">
              <div class="accordion-body">
                Nuestro horario de atención es de lunes a viernes de 8:00 AM a 5:00 PM y los sábados de 9:00 AM a 1:00 PM.
              </div>
            </div>
          </div>
          <div class="accordion-item">
            <h2 class="accordion-header" id="headingTwo">
              <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
               2. ¿Dónde puedo ver los turnos?
              </button>
            </h2>
            <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo" data-bs-parent="#faqAccordion">
              <div class="accordion-body">
                Puede ver la agenda de turnos en nuestra misma página web, en la sección "turnos de nuestra clínica".
              </div>
            </div>
          </div>
          <div class="accordion-item">
            <h2 class="accordion-header" id="headingTree">
              <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTree" aria-expanded="false" aria-controls="collapseTree">
               3. ¿Necesito cobertura médica para ser atendido?
              </button>
            </h2>
            <div id="collapseTree" class="accordion-collapse collapse" aria-labelledby="headingTree" data-bs-parent="#faqAccordion">
              <div class="accordion-body">
              No, no necesitas cobertura médica para ser atendido. Ofrecemos servicios a todos, independientemente de su seguro o cobertura.
              </div>
            </div>
          </div>
          <div class="accordion-item">
            <h2 class="accordion-header" id="headingFour">
              <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseFour" aria-expanded="false" aria-controls="collapseFour">
               4. ¿La clínica con qué especificaciones cuenta?
              </button>
            </h2>
            <div id="collapseFour" class="accordion-collapse collapse" aria-labelledby="headingFour" data-bs-parent="#faqAccordion">
              <div class="accordion-body">
              Nuestra clínica cuenta con instalaciones modernas, tecnología avanzada, personal altamente calificado, y áreas especializadas para atención médica, urgencias, y servicios de diagnóstico.
              </div>
            </div>
          </div>
          <div class="accordion-item">
            <h2 class="accordion-header" id="headingFive">
              <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseFive" aria-expanded="false" aria-controls="collapseFive">
               6. ¿Donde está ubicada la clínica?
              </button>
            </h2>
            <div id="collapseFive" class="accordion-collapse collapse" aria-labelledby="headingFive" data-bs-parent="#faqAccordion">
              <div class="accordion-body">
              
Nuestra clínica está ubicada en Argentina, en Tandil. Contamos con fácil acceso y estacionamiento para comodidad de nuestros pacientes.
            </div>
          </div>
      </section>

<?php require_once './templates/layout/footer.phtml';
?>