<?php require_once 'layout/header.php'; ?>
    <div class="container d-flex align-items-center justify-content-center" style="min-height: 80vh;">
        <div class="col-md-4">
          <h3 class="text-center mb-2">Inicio de Sesión — La Clínica</h3>
          <form action="login" method="POST" class="login-form"> 
            <div class="mb-3 text-center">
              <img src="images/logo-comun.png" alt="Imagen de Usuario" class="img-fluid" style="max-height: 180px;"> <!-- Ajusta la altura si es necesario -->
            </div>
            <div class="mb-3">
              <label for="usuario" class="form-label">Usuario</label>
              <input type="text" class="form-control" id="usuario" name="usuario" placeholder="Ingrese usuario" required>
            </div>
            <div class="mb-3">
              <label for="password" class="form-label">Contraseña</label>
              <input type="password" class="form-control" id="password" name="password" placeholder="********" required>
            </div>
            <div class="d-grid">
              <button type="submit" class="btn btn-primary btn-custom">Ingresar</button>
            </div>
          </form>
        </div>
      </div>
      <?php require_once 'layout/footer.php'; ?>
