<?php require_once './templates/layout/header.phtml'; 
//Agregar estilo al error.
  if ($error) {
    echo $error;
  }?>
    <div class="container d-flex align-items-center justify-content-center" style="min-height: 80vh;">
        <div class="col-md-4">
          <h3 class="text-center mb-2">Inicio de Sesión</h3>

          <form action="login" method="POST" class="login-form"> 
            <div class="mb-3 text-center">
              <img src="images/logo-comun.png" alt="Imagen de Usuario" class="img-fluid" style="max-height: 180px;"> 
            </div>
            <div class="mb-3">
              <label for="usuario" class="form-label">Usuario</label>
              <input type="text" class="form-control" id="user" name="user" placeholder="Ingrese usuario" >
            </div>
            <div class="mb-3">
              <label for="password" class="form-label">Contraseña</label>
              <input type="password" class="form-control" id="password" name="password" placeholder="********" >
            </div>
            <div class="d-grid">
              <button type="submit" class="btn btn-primary btn-custom">Ingresar</button>
            </div>
          </form>
        </div>
      </div>
      <?php require_once './templates/layout/footer.phtml'; ?>