<?php require_once './templates/layout/header.phtml';?>

  <div class="container mt-5">
    <h1 class="text-center mb-4">Panel de Control y Estadística</h1>
    <section>
    <!--imprimir tabla turnos -->
        <?php require_once './templates/tablas/tableTurns.phtml'; 
        //require_once './templates/tablas/tablecategories.phtml';?>

            


<?php require_once './templates/layout/footer.phtml';?>