
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>La Clínica — Centro Médico</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="css/style.css">
</head>
<body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <a class="navbar-brand" href="#">La Clínica</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item"><a class="nav-link" href="<?= BASE_URL?>home">Inicio</a></li>
                    <li class="nav-item"><a class="nav-link" href="<?= BASE_URL?>turnos">Turnos</a></li>
                    <li class="nav-item"><a class="nav-link" href="<?= BASE_URL?>faq">FAQ</a></li>
                    <li class="nav-item"><a class="nav-link" href="<?= BASE_URL?>showLogin">Iniciar Sesión</a></li>
                </ul>
            </div>
        </div>
    </nav>
